package adformat

import (
	"fmt"
	"strconv"
	"strings"
)

// Well-known asset names, kept for parity with the old model
// (admodels/types.FormatAsset* constants).
const (
	AssetNameBanner = "banner"
	AssetNameMain   = "main"
	AssetNameIcon   = "icon"
	AssetNameLogo   = "logo"
)

// Thumb describes one autogenerated thumbnail size for an asset —
// structured replacement for the old undocumented mini-DSL
// (`thumbs: ["250x", "350x", "500x"]`, §3.2.1). Height is optional
// (0 = auto, keep the source aspect ratio).
type Thumb struct {
	Width  int `json:"width,omitempty" yaml:"width,omitempty"`
	Height int `json:"height,omitempty" yaml:"height,omitempty"`
}

// FocalPoint declares whether this asset role supports attaching an anchor
// point on the image/video content, and what to assume if the advertiser
// did not provide one. This is purely positioning metadata — the file
// itself is never modified or cropped by adformat or the ad server; the
// display client (widget/app) uses the anchor (typically via a CSS
// object-position-like mechanism) to keep the important area in frame when
// rendering the same file at a different aspect ratio (MGID-style native
// "focus point", §3.2.1). The actual anchor chosen for one particular
// uploaded file is data of that creative, not part of the format schema.
type FocalPoint struct {
	// Enabled: whether the advertiser/editor may pin a focal point for
	// this asset.
	Enabled bool `json:"enabled,omitempty" yaml:"enabled,omitempty"`

	// Default anchor used when the advertiser did not specify one.
	// [0,0] = top-left, [0.5,0.5] = center, [1,1] = bottom-right.
	Default [2]float64 `json:"default,omitempty" yaml:"default,omitempty"`
}

// SafeZone declares edge insets (as fractions of the asset's own
// width/height, 0..1) that the display client must keep free of overlaid
// interface chrome (logo, countdown timer, skip/close/CTA button, §3.2.1
// gap #2). Exactly like FocalPoint, this is pure positioning metadata: the
// asset file itself is never cropped or modified by adformat or the ad
// server, the display client is responsible for keeping this area in mind
// when compositing its own controls over the creative.
type SafeZone struct {
	Top    float64 `json:"top,omitempty" yaml:"top,omitempty"`
	Right  float64 `json:"right,omitempty" yaml:"right,omitempty"`
	Bottom float64 `json:"bottom,omitempty" yaml:"bottom,omitempty"`
	Left   float64 `json:"left,omitempty" yaml:"left,omitempty"`
}

// AltTextRequirement declares whether this asset role must be accompanied
// by an accessibility description supplied together with the file, and how
// long that description may be (§3.2.1 gap #3, increasingly required by
// exchanges). Just like FocalPoint's default anchor, this only describes
// the *requirement*; the actual text for one uploaded file is data of that
// creative instance, not part of the format schema.
type AltTextRequirement struct {
	Required  bool `json:"required,omitempty" yaml:"required,omitempty"`
	MaxLength int  `json:"max_length,omitempty" yaml:"max_length,omitempty"`
}

// AssetRequirement describes a requirement for one media file within an ad
// creative (was admodels/types.FormatFileRequirement).
type AssetRequirement struct {
	// Required marks the asset as mandatory when it is active (see
	// Condition below).
	Required bool `json:"required,omitempty" yaml:"required,omitempty"`

	// Name of the asset (optional for the first/only asset, defaults to
	// "main").
	Name string `json:"name,omitempty" yaml:"name,omitempty"`

	// Resizable: the platform may scale this file to fit the target size
	// (was "adjust_size" — renamed for clarity, §3.2.1).
	Resizable bool `json:"resizable,omitempty" yaml:"resizable,omitempty"`

	// Width/Height: a "preferred" exact size for preview/fit purposes —
	// does not participate in range validation, that is always the
	// explicit Min/Max* pair below (§3.2.1). Left unset when only a
	// range is meaningful.
	Width  int `json:"width,omitempty" yaml:"width,omitempty"`
	Height int `json:"height,omitempty" yaml:"height,omitempty"`

	// MinWidth/MaxWidth, MinHeight/MaxHeight: explicit allowed size
	// range in pixels for image/video content (renamed from the
	// old ambiguous width/min_width pair, §3.2.1).
	MinWidth  int `json:"min_width,omitempty" yaml:"min_width,omitempty"`
	MaxWidth  int `json:"max_width,omitempty" yaml:"max_width,omitempty"`
	MinHeight int `json:"min_height,omitempty" yaml:"min_height,omitempty"`
	MaxHeight int `json:"max_height,omitempty" yaml:"max_height,omitempty"`

	// AspectRatio is a direct "W:H" proportion (e.g. "1.91:1", "16:9")
	// offered as a more readable alternative/addition to a Min/MaxWidth
	// + Min/MaxHeight range, matching how many real-world exchange specs
	// (Facebook/Google-style) describe size constraints (§3.2.1 gap #1).
	// When set together with a width/height range, both must be
	// satisfied. See AspectRatioValue/MatchesAspectRatio.
	AspectRatio string `json:"aspect_ratio,omitempty" yaml:"aspect_ratio,omitempty"`

	// AllowAnimated/AllowSound: permissions for the asset content (was
	// "animated"/"sound" — renamed since these describe a requirement,
	// not a fact about a specific uploaded file, §3.2.1).
	AllowAnimated bool `json:"allow_animated,omitempty" yaml:"allow_animated,omitempty"`
	AllowSound    bool `json:"allow_sound,omitempty" yaml:"allow_sound,omitempty"`

	// DurationMin/DurationMax: allowed video/audio duration range in
	// seconds. Zero means "no constraint" on that bound.
	DurationMin float64 `json:"duration_min,omitempty" yaml:"duration_min,omitempty"`
	DurationMax float64 `json:"duration_max,omitempty" yaml:"duration_max,omitempty"`

	// BitrateMin/BitrateMax: allowed video/audio bitrate range in kbps
	// (0 = no constraint on that bound). Closes the §3.2.1 gap #4 found
	// in stricter TV/VAST specs, which the old duration-only model could
	// not express.
	BitrateMin int `json:"bitrate_min,omitempty" yaml:"bitrate_min,omitempty"`
	BitrateMax int `json:"bitrate_max,omitempty" yaml:"bitrate_max,omitempty"`

	// AllowedCodecs restricts video/audio encoding (e.g. "h264", "vp9",
	// "av1", "aac") — empty means "any codec is allowed" (§3.2.1 gap #4).
	AllowedCodecs []string `json:"allowed_codecs,omitempty" yaml:"allowed_codecs,omitempty"`

	// AllowedFramerates restricts video frame rate to one of the given
	// values in fps — empty means "any frame rate is allowed" (§3.2.1
	// gap #4; several TV/VAST specs only accept exact rates like
	// 25/29.97/30 rather than a free-form range).
	AllowedFramerates []float64 `json:"allowed_framerates,omitempty" yaml:"allowed_framerates,omitempty"`

	// MaxFileSize: maximum allowed file weight in bytes (0 = no limit) —
	// closes a real gap found while researching playable/rich-media
	// specs (§3.2.2), which almost universally cap file size.
	MaxFileSize int64 `json:"max_file_size,omitempty" yaml:"max_file_size,omitempty"`

	// FocalPoint: optional focus-point metadata (§3.2.1).
	FocalPoint *FocalPoint `json:"focal_point,omitempty" yaml:"focal_point,omitempty"`

	// SafeZone: optional edge-inset metadata, symmetric to FocalPoint
	// (§3.2.1 gap #2).
	SafeZone *SafeZone `json:"safe_zone,omitempty" yaml:"safe_zone,omitempty"`

	// AltText: optional accessibility-text requirement (§3.2.1 gap #3).
	AltText *AltTextRequirement `json:"alt_text,omitempty" yaml:"alt_text,omitempty"`

	// Thumbs: structured autogenerated thumbnail sizes (§3.2.1).
	Thumbs []Thumb `json:"thumbs,omitempty" yaml:"thumbs,omitempty"`

	// AllowedTypes of files for this particular asset — either a short
	// category (image/video/html5/sound) or an exact MIME type
	// (image/jpeg) — both forms are intentionally supported.
	AllowedTypes []string `json:"allowed_types,omitempty" yaml:"allowed_types,omitempty"`

	// MinCount/MaxCount: how many instances of this asset one ad
	// creative carries (§3.2, п.2). See
	// GetMinCount/GetMaxCount/IsMultiple/RangeCount. MaxCount == -1
	// means unlimited. Only legitimate when every instance is
	// guaranteed to be part of one advertiser's single submission —
	// see §3.0.
	MinCount int `json:"min_count,omitempty" yaml:"min_count,omitempty"`
	MaxCount int `json:"max_count,omitempty" yaml:"max_count,omitempty"`

	// Condition controls when this asset is active (§3.2.5).
	Condition *Condition `json:"condition,omitempty" yaml:"condition,omitempty"`

	// NavigateTo names the screen this asset (e.g. a tappable hotspot
	// image) switches the creative to when activated (§3.2.11).
	// "$back"/"$close" are reserved commands, not screen names.
	NavigateTo string `json:"navigate_to,omitempty" yaml:"navigate_to,omitempty"`

	// Bindings associate this asset with external protocol
	// representations (OpenRTB Native image/video asset, ...) —
	// §3.2.12. Replaces the old, always-empty FormatFileRequirement.ID.
	Bindings []Binding `json:"bindings,omitempty" yaml:"bindings,omitempty"`
}

// MinMaxWidth sizes, mirroring the semantics of the old model's method of
// the same name (a bare Width with no MinWidth means an exact size).
func (a AssetRequirement) MinMaxWidth() (mn, mx int) {
	if a.MinWidth > 0 {
		return a.MinWidth, a.MaxWidth
	}
	return a.Width, a.Width
}

// MinMaxHeight sizes, symmetric to MinMaxWidth.
func (a AssetRequirement) MinMaxHeight() (mn, mx int) {
	if a.MinHeight > 0 {
		return a.MinHeight, a.MaxHeight
	}
	return a.Height, a.Height
}

// IsRequired asset — unlike the old model, this is a pure getter derived
// from Required || MinCount>0 (no more mutating IsMain() side effect on
// first call, see the bug noted in §2).
func (a AssetRequirement) IsRequired() bool {
	return a.Required || a.MinCount > 0
}

// IsMain asset (the default asset of a Config when no explicit name is
// given elsewhere).
func (a AssetRequirement) IsMain() bool {
	return a.GetName() == AssetNameMain
}

// GetName of the asset, defaulting to "main".
func (a AssetRequirement) GetName() string {
	if a.Name == "" {
		return AssetNameMain
	}
	return a.Name
}

// IsVideoSupport of the file.
func (a AssetRequirement) IsVideoSupport() bool {
	return a.IsMimeTypeSupport("video")
}

// IsImageSupport of the file.
func (a AssetRequirement) IsImageSupport() bool {
	return a.IsMimeTypeSupport("image")
}

// IsSoundSupport of the file.
func (a AssetRequirement) IsSoundSupport() bool {
	return a.IsMimeTypeSupport("sound")
}

// IsHTML5Support of the file.
func (a AssetRequirement) IsHTML5Support() bool {
	return a.IsMimeTypeSupport("html5")
}

// IsFixedSize reports whether this asset requires an exact size (no
// range).
func (a AssetRequirement) IsFixedSize() bool {
	return a.Width > 0 && a.MinWidth == 0 && a.MaxWidth == 0 &&
		a.Height > 0 && a.MinHeight == 0 && a.MaxHeight == 0
}

// ParseAspectRatio parses a "W:H" proportion string (e.g. "1.91:1",
// "16:9") into its numeric components. Both parts must be positive
// numbers.
func ParseAspectRatio(s string) (w, h float64, err error) {
	parts := strings.SplitN(s, ":", 2)
	if len(parts) != 2 {
		return 0, 0, fmt.Errorf("adformat: invalid aspect_ratio %q, expected format \"W:H\"", s)
	}
	w, errW := strconv.ParseFloat(strings.TrimSpace(parts[0]), 64)
	h, errH := strconv.ParseFloat(strings.TrimSpace(parts[1]), 64)
	if errW != nil || errH != nil || w <= 0 || h <= 0 {
		return 0, 0, fmt.Errorf("adformat: invalid aspect_ratio %q, expected format \"W:H\" with positive numbers", s)
	}
	return w, h, nil
}

// AspectRatioValue parses AssetRequirement.AspectRatio, reporting ok=false
// when it is empty or malformed.
func (a AssetRequirement) AspectRatioValue() (w, h float64, ok bool) {
	if a.AspectRatio == "" {
		return 0, 0, false
	}
	w, h, err := ParseAspectRatio(a.AspectRatio)
	return w, h, err == nil
}

// MatchesAspectRatio reports whether the given pixel dimensions satisfy
// AspectRatio within a small relative tolerance (to tolerate integer
// rounding of real image dimensions). Always true when AspectRatio is not
// set.
func (a AssetRequirement) MatchesAspectRatio(width, height int) bool {
	rw, rh, ok := a.AspectRatioValue()
	if !ok {
		return a.AspectRatio == ""
	}
	if width <= 0 || height <= 0 {
		return false
	}
	const tolerance = 0.02 // 2% relative tolerance
	target := rw / rh
	actual := float64(width) / float64(height)
	diff := actual - target
	if diff < 0 {
		diff = -diff
	}
	return diff/target <= tolerance
}

// SupportsCodec reports whether codec is allowed by AllowedCodecs (empty
// list means any codec is allowed).
func (a AssetRequirement) SupportsCodec(codec string) bool {
	if len(a.AllowedCodecs) == 0 {
		return true
	}
	for _, c := range a.AllowedCodecs {
		if strings.EqualFold(c, codec) {
			return true
		}
	}
	return false
}

// SupportsFramerate reports whether fps is allowed by AllowedFramerates
// (empty list means any frame rate is allowed).
func (a AssetRequirement) SupportsFramerate(fps float64) bool {
	if len(a.AllowedFramerates) == 0 {
		return true
	}
	for _, f := range a.AllowedFramerates {
		if f == fps {
			return true
		}
	}
	return false
}

// IsMimeTypeSupport of the file — allowed_types is either a short
// category ("image") or an exact MIME type ("image/jpeg"); an empty list
// means "any type is allowed" (§3.2.1).
func (a AssetRequirement) IsMimeTypeSupport(mimePrefix string) bool {
	if len(a.AllowedTypes) == 0 {
		return true
	}
	for _, tp := range a.AllowedTypes {
		if tp == mimePrefix || strings.HasPrefix(tp, mimePrefix+"/") {
			return true
		}
	}
	return false
}

// GetMinCount effective minimal number of instances of this asset within
// one ad creative (§3.2, п.2).
func (a AssetRequirement) GetMinCount() int {
	mn, _ := effectiveCount(a.MinCount, a.MaxCount, a.Required)
	return mn
}

// GetMaxCount effective maximal number of instances (-1 = unlimited).
func (a AssetRequirement) GetMaxCount() int {
	_, mx := effectiveCount(a.MinCount, a.MaxCount, a.Required)
	return mx
}

// RangeCount returns the effective (min, max) instance-count range.
func (a AssetRequirement) RangeCount() (min, max int) {
	return effectiveCount(a.MinCount, a.MaxCount, a.Required)
}

// IsMultiple reports whether this asset may have more than one instance.
func (a AssetRequirement) IsMultiple() bool {
	return isMultipleCount(a.GetMaxCount())
}

// SoftEqual compares two asset requirements for compatibility purposes
// (used by Config.Intersec), same relaxed matching rules as the old
// model plus a symmetric comparison of the effective instance-count
// ranges via compareAspect.
func (a AssetRequirement) SoftEqual(asset AssetRequirement) bool {
	if a.Name != asset.Name && (!a.IsMain() || !asset.IsMain()) {
		return false
	}
	r := len(a.AllowedTypes) == 0 || len(asset.AllowedTypes) == 0
	if !r {
		for _, mime := range asset.AllowedTypes {
			if a.IsMimeTypeSupport(mime) {
				r = true
				break
			}
		}
	}
	if !r {
		return false
	}
	switch {
	case a.MinWidth <= 0 && asset.MinWidth <= 0 && a.MinHeight <= 0 && asset.MinHeight <= 0:
		r = a.Width == asset.Width && a.Height == asset.Height
	case (a.MinWidth > 0 && asset.MinWidth <= 0) || (a.MinHeight > 0 && asset.MinHeight <= 0):
		r = false
	default:
		r = compareAspect(a.MaxWidth, a.MinWidth, asset.MaxWidth, asset.MinWidth) == 0 &&
			compareAspect(a.MaxHeight, a.MinHeight, asset.MaxHeight, asset.MinHeight) == 0
	}
	return r
}
